### PR TITLE
don't generate a suffix for _, it's an api change

### PR DESCRIPTION
**Pull request by jappeace**

### CODE REVIEW

**Comment by parsonsmatt** [comment]
I'm curious on the motivation for this. The function is named `gen_` precisely because it appends the `_` suffix. This was done in the style of the `lucid` library, which avoids name clashes with `Prelude` functions and Haskell keywords by appending a `_` uniformly to all element names.

You can define a new function `genNoSuffix` that doesn't include the suffix which will not break every downstream consumer.

**Comment by jappeace** [comment]
It used to be like that:  https://github.com/layer-3-communications/reflex-dom-helpers/commit/6b506fa1c2c3925e59d86b1a88012d20ac969299#diff-424f62edad2e9b4870dd761ab4222595L23
but after using it for a bit I don't like having no _ as it causes a lot of clashes

**Comment by parsonsmatt** [comment]
I should have documented this better :) If you want no suffixes, then the intent was to do:

```haskell
import qualified Reflex.Tags.Simple as HTML
import qualified Reflex.Tags.AttrPrime as Attr'
import qualified Reflex.Tags.DynAttr as DynAttr
-- etc:
-- and then write code like:

  DynAttr.div ... Attr'.span ... HTML.ul
```

Or, you could use the suffixed versions, and write:

```haskell
import Reflex.Tags

   divDynAttr ... span' ... ul_
```

etc.

It appears that your previous PR broke this intent, though.

**Comment by jappeace** [comment]
I changed the behavior to match original intend in: https://github.com/layer-3-communications/reflex-dom-helpers/pull/6/files

I like having choice.

**Pull request closed without merging**
